# Generated by Django 5.2.5 on 2025-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0002_alter_stone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='stones/qrcodes/'),
        ),
    ]
