# Generated by Django 5.2.5 on 2025-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0003_stone_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
