# Generated by Django 5.2.5 on 2025-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0004_stone_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stone',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stone',
            name='image',
            field=models.ImageField(blank=True, upload_to='stones/images'),
        ),
    ]
