# Generated by Django 5.2.5 on 2025-08-19 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0005_stone_latitude_stone_longitude_alter_stone_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stones.stone')),
            ],
        ),
    ]
