# Generated by Django 5.2.5 on 2025-08-22 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='stones/finder_images')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finder_comments', to='stones.stone')),
            ],
        ),
    ]
