# Generated by Django 5.2.5 on 2025-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0007_findercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findercomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='stones/images/finder_images'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='image',
            field=models.ImageField(blank=True, upload_to='stones/images/stone_images'),
        ),
    ]
