# Generated by Django 5.2.5 on 2025-08-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0008_alter_findercomment_image_alter_stone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findercomment',
            name='stone',
        ),
        migrations.AddField(
            model_name='stone',
            name='finder_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stone', to='stones.findercomment'),
        ),
    ]
