# Generated by Django 5.2.5 on 2025-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0009_remove_findercomment_stone_stone_finder_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stone',
            constraint=models.UniqueConstraint(fields=('title', 'latitude', 'longitude'), name='unique_stone_location'),
        ),
    ]
