# Generated by Django 5.2.5 on 2025-10-14 15:26

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0010_stone_unique_stone_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
